[package]
name = "spel-katalog-parse"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
thiserror.workspace = true
tinyvec = { version = "1.9.0", features = ["alloc", "serde"] }

[lints]
workspace = true
