[package]
name = "spel-katalog-log-view"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
derive_more = { workspace = true, features = ["deref", "deref_mut"] }
flume.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
iced_widget.workspace = true
iced_aw = { workspace = true, features = ["menu"] }
log.workspace = true
smol.workspace = true
spel-katalog-log.workspace = true
spel-katalog-widget.workspace = true
spel-katalog-assets.workspace = true
tap.workspace = true

[lints]
workspace = true
