[graph]
targets = [
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
	# paste, should be safe as it is compile time only, and feature complete
	"RUSTSEC-2024-0436",
	# instant, required by dependencies
	"RUSTSEC-2024-0384",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
	"Apache-2.0 WITH LLVM-exception",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"Unicode-3.0",
	"NCSA",
	"Zlib",
	"ISC",
	"BSL-1.0",
	"CC0-1.0",
]
confidence-threshold = 0.8
exceptions = [
]

[licenses.private]
ignore = false
registries = [
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
]
deny = [
]
skip = [
]
skip-tree = [
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
]

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
