[Theme]
help = "Theme to use"
variants = [
	"Light",
	"Dark",
	"SolarizedLight",
	"SolarizedDark",
	"GruvboxLight",
	"GruvboxDark",
	"Dracula",
	"Nord",
	"CatppuccinLatte",
	"CatppuccinFrappe",
	"CatppuccinMacchiato",
	"CatppuccinMocha",
	"TokyoNight",
	"TokyoNightStorm",
	"TokyoNightLight",
	"KanagawaWave",
	"KanagawaDragon",
	"KanagawaLotus",
	"Moonfly",
	"Nightfly",
	"Oxocarbon",
	"Ferra",
]
default = "Dark"

[Show]
help = "How to handle hidden games"
variants = ["Apparent", "Hidden", "All"]
default = "Apparent"

[UnloadThumbnails]
title = "Unload Covered Thumbnails"
help = "Should thumbnails be unloaded when now shown"
variants = ["Yes", "No"]
default = "Yes"

[FilterMode]
title = "Filter"
help = "How to filter games"
variants = ["Filter", "Search", "Regex"]
default = "Search"

[UseGamescope]
title = "Use Gamescope"
help = "Should gamescope be used"
variants = ["Yes", "No"]
default = "No"

[GamescopeExe]
title = "Gamescope Executable"
help = "Path to gamescope executable"
path = "/usr/bin/gamescope"

[SandboxMode]
title = "Sandbox Tool"
help = "How to sandbox games"
variants = ["Firejail", "Bubblewrap"]
default = "Firejail"

[Load]
title = "Which Games to Load"
help = "Should lutris and/or native games be loaded"
variants = ["Lutris", "Native", "Both", "None"]
default = "Both"

[OnRun]
title = "On Run"
help = "Should any information be opened when running game"
variants = ["Process", "Info", "None"]
default = "None"

[SortBy]
help = "How to sort games"
variants = ["Added", "Name"]
default = "Added"

[SortDir]
title = "Sort Direction"
help = "Direction to sort in"
variants = ["Forward", "Reverse"]
default = "Forward"

[Network]
help = "Should network be enabled"
variants = ["Disabled", "Enabled"]
default = "Disabled"

[LutrisExe]
title = "Lutris Executable"
help = "Path to lutris executable"
path = "/usr/bin/lutris"

[FirejailExe]
title = "Firejail Executable"
help = "Path to firejail executable"
path = "/usr/bin/firejail"

[BubblewrapExe]
title = "Bubblewrap Executable"
help = "Path to bwrap executable"
path = "/usr/bin/bwrap"

[UmuRunExe]
title = "UMU Executable"
help = "Path to umu-run executable"
path = "/usr/bin/umu-run"

[ShellExe]
title = "Shell executable"
help = "Path to shell executable"
path = "/usr/bin/bash"

[TermCommand]
title = "Terminal Command"
help = "Arguments prepended to command to run in terminal"
string = "/usr/bin/urxvt -e"

[DllOverrides]
title = "Wine Dll Overrides"
help = "Dlls to override with \"native,builtin\", separated by ';'"
string = ""

[SandboxExtras]
title = "Sandbox Extras"
help = "Additional paths which may be read from sandbox, separated by ';'"
string = ""

[CoverartDir]
title = "Coverart Directory"
help = "Path to coverart directory"
path = "{DATA}/lutris/coverart"

[LutrisDb]
title = "Lutris Database"
help = "Path to lutris game database"
path = "{DATA}/lutris/pga.db"

[CompToolsDir]
title = "Compatability tools"
help = "Path to default compatability tool directory"
path = "{DATA}/umu/compatibilitytools"

[YmlDir]
title = "Game Config Directory"
help = "Path to lutris game yml config directory"
path = "{CONFIG}/lutris/games"

[ConfigDir]
title = "Config Directory"
help = "Path application configuration directory"
path = "{CONFIG}/spel-katalog/"

[CacheDir]
title = "Cache Directory"
help = "Path to cache directory"
path = "{CACHE}/spel-katalog/"

[InstallLocation]
title = "Game Install Location"
help = "Where to install games to"
path = "{HOME}/Games"

[InstallSource]
title = "Game Install Source"
help = "Where to open install dialog"
path = ""

[InstallLocale]
title = "Default Install Locale"
help = "Locale to prefill installer with"
string = ""

[ThmubnailSource]
title = "Thumbnail Source Directory"
help = "Where to open thumbnail dialog"
path = "{HOME}/Pictures"
