[package]
name = "spel-katalog-tag-filter"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
iced_core.workspace = true
iced_runtime.workspace = true
iced_widget.workspace = true
iced_aw = { workspace = true, features = ["sidebar", "context_menu"]}
itertools.workspace = true
log.workspace = true
rustc-hash.workspace = true
spel-katalog-common.workspace = true
spel-katalog-formats.workspace = true
spel-katalog-widget.workspace = true
spel-katalog-list-menu.workspace = true
tap.workspace = true

[lints]
workspace = true
